### ISSUE TITLE
[Feature request] If the user is not logged in, the Favorite page could let them sign in.

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/e-team#100]
If the user is not signed in, the Favorite page could either let them sign in or display a friendly message let them know what is going on in this page instead of a black page. 

environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Without sign in go to Favorite page
expected result:Either a message say you need to sign in to be able to use the feature or login function in Favorite page if the user is not signed in. 
actual result: A blank page.

**Comment by Jemuelle4** [comment]
Alternatively, the "Favorite" navigation button can be removed when a user is not signed in.

**Comment by nsnatthapat** [comment]
Valid issue that we will work on in coming sprint

**Comment by Preciousstowers** [comment]
Valid issue. Originally, it did lead back to the signUp/login page but it broke during deployment. We will revisit this issue.

**Comment by nsnatthapat** [comment]
duplicate #118
