### ISSUE TITLE
[Major] There is no feedback when unable to register

### ISSUE THREAD

**Issue by meghajain2** [info442-aut21/e-team#102]
When signing up for the web app, if a user tries to fill in their information and all the information is not there, there is no feedback to tell the user what is missing or what they are doing wrong to try to fix it. For example, I didn't upload a profile picture and the app didn't say anything just wouldn't let me register as I continued pressing the button.

Environment: Chrome Version 96.0.4664.55 on MacOS Big Sur
Steps to reproduce: Go to https://discoveryhub-86001.firebaseapp.com/ and click sign up/login in the right-hand corner, Fill in some information (everything except the profile picture, for example) and click submit
Expected Output: Should either work by making the profile picture optional or show an error message saying the profile picture is required
Actual Output: No feedback and the submit button didn't work when I didn't add a profile picture. I don't know if it was because the submit button wasn't working or if I didn't fill out the sign up form correctly.

**Comment by Preciousstowers** [comment]
Duplicate issue. Original issue is #82
