### ISSUE TITLE
[Enhancement] sign up/login and register popup appear after return to home page from every page

### ISSUE THREAD

**Issue by ayun6** [info442-aut21/e-team#104]
the sign up and register popup appears after the user returns to the home page from other pages on the site. 
this makes it difficult to work on the website as the user has to constantly x out of the popup to continue using the site.

**Comment by Preciousstowers** [comment]
Similar issue to #81, #83 and #99. This will be addressed when working on the pop-up functionality.

**Comment by Sneha-8** [comment]
Fixed with our recent commit #134
