### ISSUE TITLE
[Enhancement] blank page for certain locations

### ISSUE THREAD

**Issue by ayun6** [info442-aut21/e-team#105]
when selecting the geographic filters, although there are many options, certain locations such as Vancouver, Kent, Spokane Valley, Everett, and Renton all render a blank page. Maybe if there are no current tutoring places available in those locations, a message could be displayed alerting the user of this.

**Comment by victoriathegr8** [comment]
valid issue - displaying a message if there is no data that matches filter criteria is a good idea!

**Comment by Sneha-8** [comment]
duplicate for #92
