### ISSUE TITLE
[Minor] Space is not registered as a special character for password

### ISSUE THREAD

**Issue by matthewputra** [info442-aut21/e-team#108]
Environment: Google Chrome Version 95.0.4638.69 (Official Build) (x86_64)
Steps to reproduce: Make an account and then include space as the password
Expected result: The "Password has special characters." line to be checked green
Actual result: The "Password has special characters." line is crossed red
Link to the special characters lists that are defined by an organization for passwords
https://owasp.org/www-community/password-special-characters

**Comment by Preciousstowers** [comment]
Valid issue! This will be fixed when working on our custom sign-up form functionality!
