### ISSUE TITLE
[Major] User is allowed to change their email input when editing profile that doesn't meet email standards -- this change does not save and cannot be used to log in because of an inconsistency with the requirements of signing up

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/e-team#111]
The user authentication and editing process seem a bit tricky here and the rules aren't aligned. The root of this issue seems to be an inconsistency with restrictions when editing one's user profile. When you edit your profile email, you aren't restricted to having any type of standard email format (e.g., you can type in 1234 and it will accept that input). When you try logging in with those credentials after signing out, you will be met with an error when typing in your email. But if you try logging in once again with the same email and password in the "Sign in with email" button, it works and saves the information from before. I believe that editing the profile function is completely inoperable at this moment in time.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

Reproducing this issue: Home page > SignUp/Login > Sign in with firebase authentication email prompt > Fill out the fields with my information > Profile > Click out of the popup > Edit profile > Type in random characters that don't follow email rules > Done > Log out > Click SignUp/Login > Enter what was changed for email into the email field but use the same password > prompt blocks you

The first expected result of this user flow was to have some sort of restriction on editing the profile email to match that of when a user signs up. What was received was no restrictions or indication that what I typed in was invalid for that profile page. The second expected result was to be able to log into the same account using the edited email and the same password. What was received was an error message that doesn't allow me to log in using that new "email" I had edited in my profile page to log back into my profile due to the email standards restriction.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/72470963/142910533-4d54922a-3632-4b13-a2aa-1738e5f24ea2.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/72470963/142911613-ea7e9aec-b0ed-4e26-ba93-f2a5066ca038.png">

**Comment by victoriathegr8** [comment]
can be fixed by adding input validation to the email input box. user should not be able to press done after editing profile if validation is not complete. validation can be that the email includes an @ and . characters
