### ISSUE TITLE
[Enhencement] Default react page tag name and icon.

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/e-team#112]
<img width="233" alt="Screen Shot 2021-11-22 at 10 07 28 AM" src="https://user-images.githubusercontent.com/59670580/142912889-6d11261c-f825-40b0-b917-ca31a282562f.png">
Instead of the default react tab name and icon, you can make you owns just need one line of html I think. 
environment it was encountered in Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Open the site on a browser like Chrome
expected result: A unique page name and icon
actual result: react default name and icon.

**Comment by Sneha-8** [comment]
We will work on it, during the next sprint

**Comment by nsnatthapat** [comment]
duplicate #120

**Comment by Sneha-8** [comment]
Fixed, Added a default title and logo to the website.
