### ISSUE TITLE
[Enhencement] Nav link position 

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/e-team#114]
I think the nav link could be formatted better by puting the nav links next right to the logo, and leave the sign in sign up function on the right. 

environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Nav links on brower loke Chrome
expected result: The nav link is distincted from the sign in sign up button 
actual result:They are all on the right and a little crowed there.

**Comment by Sneha-8** [comment]
duplicate with the issues #90
