### ISSUE TITLE
[Feature Request] Turn Services, Subjects, and Platforms Available Options into Bulleted Lists

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/e-team#115]
In terms of user interaction, the way the traits are listed within each organization card is in a format similar to that of a button that compels a user like myself to click on it. For readability purposes, it would make sense to format this into a bulleted list under each section instead. This goes for every page that this format is consistent EXCEPT for the favorites page (i.e., home page, /detail/# pages).

**Comment by Sneha-8** [comment]
This was a design choice.

**Comment by Preciousstowers** [comment]
We will readjust how the cards look! Thank you for showing your perspective!
