### ISSUE TITLE
[Minor] Filtering by 'mentor' changes card size of the rendered education opportunities

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/e-team#116]
Description: Using the filter system given, we can use location, subject, platform, etc. When choosing to filter solely by 'mentor' the cards become smaller by a few pixels. I believe this has to do with the 'Sylvan Learning of Kirkland' card because it has a lot of content and offers Tutors. When you filter by mentor, it goes away and the other cards have less content, thus, they become smaller as they no longer need to render the large 'Sylvan Learning of Kirkland' card.

Expectation: Cards remain the same size regardless of what the user is filtering by

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by Sneha-8** [comment]
Duplicate, the issue created before you was #97
