### ISSUE TITLE
[Minor] Blank Screen for Not Logged In Users on Favorite Tab

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/e-team#118]
When user is not logged in but clicks on the "favorite" tab, where the url says "/userreg", it does not display anything. There's no indication if it is a feature that can only be used if you are logged in or maybe you intended it for the user to be redirected to the user registration page(judging from the name of the route). If you are not routing the users to the sign up page, I think an indication or a image/text that shows that they need to log in to have favorites would be helpful for the usability.

**Comment by Sneha-8** [comment]
Duplicate with the issue #100

**Comment by cherimarie** [comment]
I can see why this is marked as a duplicate, but for purposes of Vanessa's grade, I'm not considering it such.
