### ISSUE TITLE
[Enhancement] Add functionality to logo in header

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/e-team#119]
Description: Add a link to the logo image in the header that takes you back to the home page.

Explanation: I've used a lot of sites that have some kind of link functionality to their logo that takes you back to the main/home page of the site, so adding this feature would add a bit of consistency/familiarity to the site's navigation.

**Comment by Preciousstowers** [comment]
Thank you for sharing! We will add this in our next sprint!

**Comment by Sneha-8** [comment]
Fixed!
