### ISSUE TITLE
[Enhancement] Show that adding a profile picture in signing up is optional

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/e-team#121]
Description: Add subtext to the profile picture box on the sign up page that makes it explicitly clear that users don't have to select a profile picture to sign up. 

Explanation: A profile picture isn't necessarily required immediately for creating new accounts, and trying to go through the sign up process myself, I thought one was required here. Adding this subtext would allow users not to feel pressured to adding a picture.

**Comment by victoriathegr8** [comment]
valid - can add * to denote required fields when signing up

**Comment by cherimarie** [comment]
I like this idea. Clear communication to the user about what fields in a form are required is important for user experience.

**Comment by nsnatthapat** [comment]
Invalid due to removal of custom sign up
