### ISSUE TITLE
[Minor] Required Information

### ISSUE THREAD

**Issue by judysdesign** [info442-aut21/e-team#130]
macOS Big Sur
Version 11.6
Chrome Version 96.0.4664.55

Description: When making a new account and the user does not add a profile picture and clicks on the Sign Up button - nothing happens.

Expected: Should get a message saying that the user needs to add a profile picture because it is required before signing up.
Actual: Nothing happens.

**Comment by cherimarie** [comment]
I would consider this a major bug, as it totally prevents someone from creating an account. For phase 8 grading, though, we won't consider this a  major level issue that must be completed, because it's not fair to the team to add a requirement the day the assignment is due.

**Comment by nsnatthapat** [comment]
No option to add profile pic anymore, so this issue becomes invalid
