### ISSUE TITLE
[Major] Signing In Through Gmail Doesn't Work

### ISSUE THREAD

**Issue by talajune** [info442-aut21/e-team#81]
I signed in through Gmail, and it took me to the external Gmail login which is great. However, when I returned back to the webpage, nothing had changed/I wasn't actually signed in. The screen looks the same as it did before I "signed in" through Gmail.

Update: I actually see now that it does sign me in, but the only change I see when signed in is through the "profile" tab. Nothing about the sign up/sign in page changed, so it still gives me the option to sign up/sign in even though I am already signed in through Gmail. It would be nice to be able to see the updates confirming that I am logged in through the home page.

Used Chrome Version 95.0.4638.69 on macOS Big Sur

**Comment by naishg** [comment]
In addition, the sign in button does not produce anything. clicking it does not do anything. A suggestion for a feature that you could possibly implement is a note or of some sort that informs users that signing in has been completed.

**Comment by nsnatthapat** [comment]
Make pop-up not appear if already signed-in

**Comment by nsnatthapat** [comment]
Duplicate: https://github.com/info442-aut21/e-team/issues/88

**Comment by nsnatthapat** [comment]
Duplicate: https://github.com/info442-aut21/e-team/issues/93

**Comment by Preciousstowers** [comment]
Completed in latest deployment
