### ISSUE TITLE
[Major] Initial SignUp Submit Button doesn't log you in or take you anywhere

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/e-team#82]
Windows 11:
Google Chrome: Version 96.0.4664.45

Description: Signup button doesn't do anything

Steps to reproduce: I clicked the "SignUp/Login" button on the popup. I typed in my credentials on the SignUp side. Pressed submit, and it didn't do anything.

Expected: Close login screen and be logged in
Actual: Nothing happened that I can tell

**Comment by naishg** [comment]
In addition, the submit button does not produce anything. Clicking it does not do anything. A suggestion for a feature that you could possibly implement is a note or of some sort that prompts the users that their account has been successfully created.

**Comment by Preciousstowers** [comment]
This is a correct major issue, which is attached to User Sign up.

**Comment by nsnatthapat** [comment]
duplicate: https://github.com/info442-aut21/e-team/issues/102

**Comment by cherimarie** [comment]
Is this invalid because you're dropping the requirement for custom email auth? If so, let's add a comment to that effect.
