### ISSUE TITLE
[Minor] After you exit out from Sign up popup, the entire page goes blank

### ISSUE THREAD

**Issue by joonbot1999** [info442-aut21/e-team#83]
I clicked on signup, but when I clicked X to exit out of the pop-up, the entire page goes completely blank when I expected to be back on the previous page. However, I can work around this by clicking on DiscoveryHub logo.
environment: Chrome Version 96.0.4664.45, Omen 15
steps to reproduce: Click on signup, then click X
expected result: back to the main page
actual result: blank main page

**Comment by Preciousstowers** [comment]
Yes, this will be fixed. This can be possibly changed through the change button text function and/or browser router.

**Comment by Preciousstowers** [comment]
Completed in lastest deployment
