### ISSUE TITLE
[Feature Request] Confirm Password or See Password

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/e-team#84]
Since you can't see your password when you type it in, I would like a way to either confirm your password or have an option to see your password as you type.

**Comment by IamSuperB4** [comment]
Forgot to put a reason. This feels important since you may not have typed the password you thought and you wouldn't be able to log back in without changing your password

**Comment by victoriathegr8** [comment]
Only possible when creating custom signup, not through integrated Firebase signup.
