### ISSUE TITLE
[Major] the buttons on the homepage for selecting subjects, services, and platforms don't work

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/e-team#85]
- [Major] the buttons on the homepage for selecting subjects, services, and platforms don't work
- Firefox on Windows 10
- on opening of webpage, close out pop up and try to click on buttons under services available, subjects available, and platform available
- expected to see the services/subjects/platform available
- actual result: button clicks do nothing

**Comment by victoriathegr8** [comment]
select filters don't narrow down organization results at all

**Comment by nsnatthapat** [comment]
Unable to replicate

**Comment by cherimarie** [comment]
@nsnatthapat did you speak with the reporters and see if they could show you the bug in the environment they encountered it in? If two different people saw it, I think it's likely to be valid.
