### ISSUE TITLE
[ Minor ] on sign up page choose file for profile picture doesn't work

### ISSUE THREAD

**Issue by angelinapoltavskiy** [info442-aut21/e-team#86]
When I went to sign up, and clicked on choose file to upload profile picture nothing happens
environment: google chrome  - Version 95.0.4638.69
steps to reproduce: Open up application in google chrome, open up application, click on sign up, click on choose file under profile pic
expected result: I thought that when I clicked on choose file under profile pic I would be prompted to upload a photo
actual result: when I click on choose file, nothing happens

**Comment by victoriathegr8** [comment]
unable to replicate

**Comment by nsnatthapat** [comment]
unable to replicate

**Comment by cherimarie** [comment]
I had this experience as well, and I believe it was caused by trying to upload an image with any extension other than .jpg. It happened when I tried a .png and .jpeg, weirdly.
