### ISSUE TITLE
[Minor] A website that doesn't exist

### ISSUE THREAD

**Issue by joonbot1999** [info442-aut21/e-team#87]
When I click on a link to a website that doesn't exist (i.e. The Dinosaur Nest), the entire UI just disappears. I can work around this by refreshing the page, but wouldn't it be more prudent to not make it clickable at all?
environment: Chrome Version 96.0.4664.45, Omen 15
steps to reproduce: click the None for The Dinosaur Nest
expected result: nothing
actual result: blank UI

**Comment by nsnatthapat** [comment]
Still navigates to an invalid link

**Comment by Preciousstowers** [comment]
Valid minor issue. This will be addressed in the add org form milestone/functionality.

**Comment by cherimarie** [comment]
I'd also recommend, in the fix, adding a `target="blank"` to the links so they open in another tab. You won't be able to fully validate URLs in the form, so you should plan for occasionally having a bad one. If it opens to a 404 in a different tab, the user will be more likely to just close that tab and return to your site.

**Comment by Preciousstowers** [comment]
Completed in latest deployment
