### ISSUE TITLE
[Minor] Signed in with Gmail Correctly, Brought me back to signin/up popup

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/e-team#88]
Windows 11:
Google Chrome: Version 96.0.4664.45

I had signed up with Gmail, it appeared to work correctly. As you can see in the picture at the top right, it shows "Profile" (which is cut off by the way), instead of "SignUp/Login", so I think that means it logged me in successfully. But instead of closing the signup/login popup, it took me back to it so I had to close it myself.

Expected: Close signup/login popup and take me to the main page
Actual: Kept the signup/login popup

I attached an image, hopefully it showed up

![image](https://user-images.githubusercontent.com/16829246/142905487-1e800136-351a-4e25-88ba-83de0448612b.png)

**Comment by Preciousstowers** [comment]
Valid duplicate bug. This was previously addressed in issue #81.
