### ISSUE TITLE
[Enhencement] The filter for Geographic Location seems only have three options.

### ISSUE THREAD

**Issue by ychen023** [info442-aut21/e-team#92]
When clicking on several filters for geographic location, there is only 3 options that is Seattle, Bellevue, and Tacoma. Not sure if you will implement more to this but should only left the one you have data. 

environment it was encountered in: Chrome Version 95.0.4638.69 (Official Build) (arm64)
steps to reproduce: Clicking on different geographic location filter
expected result:Everything has cards response to the filter, or at most one do not have data. 
actual result:Only three locations have data, but the others have no cards response.

**Comment by Preciousstowers** [comment]
Valid issue. We will change/add data in homepage.js to incorporate a variety of organizations in different cities.

**Comment by victoriathegr8** [comment]
or add message on homepage when no data is returned matching criteria

**Comment by Sneha-8** [comment]
Fixed! We added a "No Results" Message to notify the user when there are no matches.
