### ISSUE TITLE
[major] entire homescreen is not mobile friendly

### ISSUE THREAD

**Issue by njkpark** [info442-aut21/e-team#96]
![5BAF8B9C-583B-4B7E-B212-0DBA29D44DA1](https://user-images.githubusercontent.com/62912422/142906926-02a2bdca-0575-43b4-8cac-6dabf8fa0d81.png)

environment: apple iphone 12 on safari

steps to reproduce: click link to website on mobile device, click “x” on the popup

Expected result: responsive and fitting homescreen of the content and features

Actual result: cards do not fit on mobile screen

**Comment by Preciousstowers** [comment]
Valid duplicate. Under issue #90.
