### ISSUE TITLE
[Major] Registering An Organization Does Nothing

### ISSUE THREAD

**Issue by Jemuelle4** [info442-aut21/e-team#98]
description: After filling out the form for "Register your organization" and clicking sign up, nothing happens
●     Windows 10 Firefox 94.0.1 (32-bit)
●     Steps to Reproduce: Click on "Register Organization" from the initial pop up page. Fill out all fields in form. Press Done.
●     expected result: A success message or an error message
●     actual result: Nothing happens

**Comment by nsnatthapat** [comment]
Invalid after tried to replicate on firefox, and
