### ISSUE TITLE
[Minor] The background of the modal/pop up should be darker or made more distinct for the pop up

### ISSUE THREAD

**Issue by meghajain2** [info442-aut21/e-team#99]
The pop up/modal in the beginning kind of blends in with the background text and there isn't much distinction to where it starts which can lead to confusion especially for those with certain disabilities. The background text should be blurred or darkened to make the modal pop more.

Enviornment: Chrome Version 96.0.4664.55 on MacOS Big Sur

**Comment by Preciousstowers** [comment]
Valid issue. We will adjust the colors in our CSS file.

**Comment by Sneha-8** [comment]
Fixed in our recent merge! #134
